### ISSUE TITLE
Pre-model download

### ISSUE THREAD

**Issue by tjulitianyi1997** [peteryuX/arcface-tf2#10] opened 2020-04-06 06:50 UTC
Hi, your pre-model is on Google Drive, I cannot download it, can you upload it to Baidu Drive or send it to my E-mail? 
Thank you very much and I wish you good health.
E-mail  1375088614@qq.com

**Comment by peteryuX** [comment] 2020-04-10 08:10
Duplicate of https://github.com/peteryuX/retinaface-tf2/issues/1

**Closed by peteryuX** 2020-04-10 08:10 UTC
